/* ==========================================
   ENGINE 5: EXPORT
   ========================================== */
const ExportEngine = {
    generateLISP: function() {
        const latlngs = MapEngine.lotPoly.getLatLngs()[0];
        proj4.defs(ConfigEngine.cad.projection, ConfigEngine.cad.proj4Def);

        const cadZone = ConfigEngine.data.cadZone || 'CA_VI';
        const cadLabel = (ConfigEngine.CAD_SYSTEMS[cadZone] || {}).label || ConfigEngine.cad.projection;
        const acad_cs = { CA_VI: 'CAHP-VIF', CA_V: 'CAHP-VF', CA_IV: 'CAHP-IVF', CA_III: 'CAHP-IIIF', WA_N: 'WAHP-NF', WA_S: 'WAHP-SF' };
        const csCode  = acad_cs[cadZone] || 'CAHP-VIF';
        const s       = ConfigEngine.state;

        // Build DPL:ParcelPts — CAD state-plane coordinate pairs from lot polygon
        const ptLines = [];
        latlngs.forEach(function(pt) {
            const ca = proj4('WGS84', ConfigEngine.cad.projection, [pt.lng, pt.lat]);
            ptLines.push('    (list ' + ca[0].toFixed(4) + ' ' + ca[1].toFixed(4) + ')');
        });

        // ── Dynamic CONFIG section ──────────────────────────────────────────────
        const configSection = [
            '(setq DPL:APN       "' + ConfigEngine.data.apn     + '")',
            '(setq DPL:Address   "' + ConfigEngine.data.address + '")',
            '(setq DPL:Rotation  ' + s.rotation.toFixed(1) + ')   ; site north degrees',
            '(setq DPL:CenterLat ' + s.lat.toFixed(8)      + ')   ; WGS84 latitude  (reference only)',
            '(setq DPL:CenterLng ' + s.lng.toFixed(8)      + ')   ; WGS84 longitude (reference only)',
            '(setq DPL:CoordCode "' + csCode + '")',
            '',
            '(setq DPL:ParcelPts',
            '  (list',
            ptLines.join('\n'),
            '  )',
            ')'
        ].join('\n');

        // ── Static skeleton body ────────────────────────────────────────────────
        // Note: \\n in JS template literal outputs \n in the .lsp file (correct LISP string escape)
        const skeleton = [
            ';;; ====================================================================',
            ';;; Draw_ParcelLot.lsp',
            ';;; ====================================================================',
            ';;; PURPOSE:',
            ';;;   1) Capture current user environment settings',
            ';;;   2) Assign drawing coordinate system using MAPCSASSIGN',
            ';;;   3) Turn on GEOMAP AERIAL',
            ';;;   4) Draw parcel boundary as a closed polyline',
            ';;;   5) Restore exact original user settings',
            ';;;',
            ';;; COMMANDS:',
            ';;;   DPL      -> Full process',
            ';;;   DPCS     -> Coordinate setup only',
            ';;;   DPLM     -> Menu',
            ';;;   InfoDPLM -> Help',
            ';;; ====================================================================',
            '',
            '(vl-load-com)',
            '',
            ';;; ==========================================================================',
            ';;; CONFIG -- generated by ProjectBook-Planner',
            ';;; APN:     ' + ConfigEngine.data.apn,
            ';;; Address: ' + ConfigEngine.data.address,
            ';;; Zone:    ' + cadLabel,
            ';;; ==========================================================================',
            '',
            configSection,
            '',
            ';;; ==========================================================================',
            ';;; SESSION STATE',
            ';;; ==========================================================================',
            '',
            '(setq DPL:*saved-vars* nil)',
            '(setq DPL:*olderror*   nil)',
            '',
            ';;; ==========================================================================',
            ';;; UTILITY: SAVE CURRENT ENVIRONMENT',
            ';;; ==========================================================================',
            '',
            '(defun DPL:SaveEnv (/)',
            '  (setq DPL:*olderror* *error*)',
            '  (setq *error* DPL:ErrorHandler)',
            '  (setq DPL:*saved-vars*',
            '    (list',
            '      (cons "CMDECHO"  (getvar "CMDECHO"))',
            '      (cons "CMDDIA"   (getvar "CMDDIA"))',
            '      (cons "FILEDIA"  (getvar "FILEDIA"))',
            '      (cons "OSMODE"   (getvar "OSMODE"))',
            '      (cons "LUNITS"   (getvar "LUNITS"))',
            '      (cons "AUNITS"   (getvar "AUNITS"))',
            '      (cons "INSUNITS" (getvar "INSUNITS"))',
            '    )',
            '  )',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; UTILITY: RESTORE SAVED ENVIRONMENT',
            ';;; ==========================================================================',
            '',
            '(defun DPL:RestoreEnv (/ pair)',
            '  (if DPL:*saved-vars*',
            '    (foreach pair DPL:*saved-vars*',
            '      (if (and pair (car pair) (cdr pair))',
            '        (setvar (car pair) (cdr pair))',
            '      )',
            '    )',
            '  )',
            '  (if DPL:*olderror* (setq *error* DPL:*olderror*))',
            '  (setq DPL:*saved-vars* nil)',
            '  (setq DPL:*olderror*   nil)',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; ERROR HANDLER',
            ';;; ==========================================================================',
            '',
            '(defun DPL:ErrorHandler (msg)',
            '  (DPL:RestoreEnv)',
            '  (if (and msg',
            '           (/= msg "Function cancelled")',
            '           (/= msg "quit / exit abort"))',
            '    (princ (strcat "\\n[ERROR] " msg))',
            '  )',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; UTILITY: VALIDATE POINT LIST',
            ';;; ==========================================================================',
            '',
            '(defun DPL:IsValidPointList (pts / ok)',
            '  (setq ok T)',
            '  (if (or (not pts) (< (length pts) 3))',
            '    (setq ok nil)',
            '    (foreach p pts',
            '      (if (or (/= (type p) (quote LIST)) (< (length p) 2))',
            '        (setq ok nil)',
            '      )',
            '    )',
            '  )',
            '  ok',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; CORE: ASSIGN COORDINATE SYSTEM',
            ';;; ==========================================================================',
            '',
            '(defun DPL:SetCoord (/)',
            '  (princ "\\n[DPCS] Assigning coordinate system...")',
            '  (command "_.MAPCSASSIGN" DPL:CoordCode)',
            '  (princ (strcat "\\n[DPCS] Assigned: " DPL:CoordCode))',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; CORE: TURN ON GEOMAP AERIAL',
            ';;; ==========================================================================',
            '',
            '(defun DPL:GeomapAerial (/)',
            '  (princ "\\n[DPL] Enabling GEOMAP AERIAL...")',
            '  (command "_.GEOMAP" "_AERIAL")',
            '  (princ "\\n[DPL] GEOMAP AERIAL enabled.")',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; CORE: DRAW PARCEL BOUNDARY',
            ';;; ==========================================================================',
            '',
            '(defun DPL:DrawBoundary (/)',
            '  (princ "\\n[DPL] Drawing parcel boundary...")',
            '  (if (DPL:IsValidPointList DPL:ParcelPts)',
            '    (progn',
            '      (apply (quote command)',
            '        (append',
            '          (list "_.PLINE")',
            '          DPL:ParcelPts',
            '          (list "_C")',
            '        )',
            '      )',
            '      (command "_.ZOOM" "_E")',
            '      (princ "\\n[DPL] Closed parcel polyline drawn.")',
            '    )',
            '    (princ "\\n[ERROR] Parcel point list is invalid.")',
            '  )',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; CORE: APPLY TEMP WORKING SETTINGS',
            ';;; ==========================================================================',
            '',
            '(defun DPL:ApplyTempEnv (/)',
            '  (setvar "CMDECHO"  0)',
            '  (setvar "CMDDIA"   0)',
            '  (setvar "FILEDIA"  0)',
            '  (setvar "OSMODE"   0)',
            '  (setvar "LUNITS"   2)   ; Decimal feet (required for state-plane coords)',
            '  (setvar "AUNITS"   0)',
            '  (setvar "INSUNITS" 2)   ; Feet',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; CORE: MAIN PROCESS',
            ';;; ==========================================================================',
            '',
            '(defun DPL:Process (/)',
            '  (DPL:SaveEnv)',
            '  (DPL:ApplyTempEnv)',
            '  (princ (strcat "\\n[DPL] APN: " DPL:APN))',
            '  (princ (strcat "\\n[DPL] " DPL:Address))',
            '  (DPL:SetCoord)',
            '  (DPL:GeomapAerial)',
            '  (DPL:DrawBoundary)',
            '  (DPL:RestoreEnv)',
            '  (princ "\\n[DPL] Complete.")',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; COMMANDS',
            ';;; ==========================================================================',
            '',
            '(defun c:DPL ()            (DPL:Process))',
            '(defun c:Draw_ParcelLot () (DPL:Process))',
            '',
            '(defun c:DPCS ()',
            '  (DPL:SaveEnv)',
            '  (DPL:ApplyTempEnv)',
            '  (DPL:SetCoord)',
            '  (DPL:GeomapAerial)',
            '  (DPL:RestoreEnv)',
            '  (princ)',
            ')',
            '',
            '(defun c:Draw_ParcelCoordSetup () (c:DPCS))',
            '',
            ';;; ==========================================================================',
            ';;; MENU',
            ';;; ==========================================================================',
            '',
            '(defun c:DPLM (/ choice)',
            '  (textscr)',
            '  (princ "\\n=======================================================")',
            '  (princ "\\n DPLM - DRAW PARCEL LOT MENU")',
            '  (princ "\\n=======================================================")',
            '  (princ (strcat "\\n APN:  " DPL:APN))',
            '  (princ (strcat "\\n Zone: " DPL:CoordCode))',
            '  (princ "\\n [DPL]  -> Coord + GEOMAP AERIAL + Draw Parcel")',
            '  (princ "\\n [DPCS] -> Coord + GEOMAP AERIAL only")',
            '  (princ "\\n=======================================================")',
            '  (initget "DPL DPCS")',
            '  (setq choice (getkword "\\nSelect Option [DPL/DPCS]: "))',
            '  (cond',
            '    ((= choice "DPL")  (c:DPL))',
            '    ((= choice "DPCS") (c:DPCS))',
            '  )',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; HELP',
            ';;; ==========================================================================',
            '',
            '(defun c:InfoDPLM ()',
            '  (textscr)',
            '  (princ "\\n=======================================================")',
            '  (princ "\\n         DPLM - DRAW PARCEL LOT UTILITIES")',
            '  (princ "\\n=======================================================")',
            '  (princ "\\n[PURPOSE]")',
            '  (princ "\\n  Saves environment, assigns coordinate system,")',
            '  (princ "\\n  enables GEOMAP AERIAL, draws parcel, restores env.")',
            '  (princ "\\n")',
            '  (princ "\\n[COMMANDS]")',
            '  (princ "\\n  DPL      -> Full sequence")',
            '  (princ "\\n  DPCS     -> Coordinate system + GEOMAP AERIAL only")',
            '  (princ "\\n  DPLM     -> Interactive menu")',
            '  (princ "\\n  InfoDPLM -> This help screen")',
            '  (princ "\\n")',
            '  (princ "\\n[SITE DATA]")',
            '  (princ (strcat "\\n  APN:        " DPL:APN))',
            '  (princ (strcat "\\n  Address:    " DPL:Address))',
            '  (princ (strcat "\\n  Zone:       " DPL:CoordCode))',
            '  (princ (strcat "\\n  Site North: " (rtos DPL:Rotation 2 1) " deg"))',
            '  (princ (strcat "\\n  Lat/Lng:    " (rtos DPL:CenterLat 2 6) " / " (rtos DPL:CenterLng 2 6)))',
            '  (princ (strcat "\\n  Vertices:   " (itoa (length DPL:ParcelPts))))',
            '  (princ "\\n=======================================================")',
            '  (princ)',
            ')',
            '',
            ';;; ==========================================================================',
            ';;; LOAD MESSAGE',
            ';;; ==========================================================================',
            '',
            '(princ "\\n=======================================================")',
            '(princ "\\n :: Draw_ParcelLot.lsp [DPL] Loaded")',
            '(princ (strcat "\\n :: APN:  " DPL:APN))',
            '(princ (strcat "\\n :: Zone: " DPL:CoordCode))',
            '(princ "\\n :: Commands: DPL | DPCS | DPLM | InfoDPLM")',
            '(princ "\\n=======================================================")',
            '(princ)'
        ].join('\n');

        document.getElementById('outputCoords').value = skeleton;

        // Persist metadata to localStorage for Python/build pipeline access
        const meta = {
            apn:      ConfigEngine.data.apn,
            address:  ConfigEngine.data.address,
            lat:      s.lat,
            lng:      s.lng,
            rotation: s.rotation,
            setbacks: s.setbacks,
            csCode:   csCode
        };
        localStorage.setItem('last_lisp_export', JSON.stringify(meta, null, 2));

        // Save session state, then download .lsp file
        this.save();
        const blob = new Blob([skeleton], { type: 'text/plain' });
        const link = document.createElement('a');
        var _addr = ConfigEngine.data.address || '';
        var _addrParts = _addr.split(/[\s,]+/);
        var _num    = _addrParts[0] || 'Site';
        var _street = _addrParts[1] || 'Parcel';
        link.download = 'Draw_ParcelLot_' + _num + '-' + _street + '.lsp';
        link.href = URL.createObjectURL(blob);
        link.click();
        URL.revokeObjectURL(link.href);
    },

    generateExcel: function() {
        const sd = window.__SITE_DEFAULTS__ || {};
        const d  = ConfigEngine.data;
        const s  = ConfigEngine.state;

        const lotSF   = (sd.lotSF && sd.lotSF > 0) ? sd.lotSF : (d.width * d.depth);
        const lotAC   = (lotSF / 43560).toFixed(3);
        const hasPolygon = (sd.parcelPolygon && sd.parcelPolygon.length > 0);

        function v(val, unit) {
            if (val == null || val === '' || val === 0 && unit) return '--';
            return unit ? val + ' ' + unit : String(val);
        }

        // ── Build section rows ──────────────────────────────────────────────────
        // Each entry: [section, field, value, source]  OR  [null, ...] for section header
        const ROWS = [];

        function sec(label) { ROWS.push({ type: 'sec', label }); }
        function row(field, value, source, even) { ROWS.push({ type: 'row', field, value, source, even }); }

        // A. Parcel Identity
        sec('A. Parcel Identity');
        row('Full street address',          v(sd.address),                     'County Assessor / ParcelQuest',                     true);
        row('APN (all parcels if combined)', v(sd.apn),                         'County Assessor / ParcelQuest',                     false);
        row('Legal description (full)',      v(sd.legalDescription),            'Deed or Assessor record',                           true);
        row('Year built (existing)',         v(sd.yearBuilt),                   'Assessor record — or Vacant if raw land',           false);
        row('Occupancy group (existing)',    v(sd.occupancyGroup),              'Building permit history or existing plans',         true);

        // B. Lot Dimensions
        sec('B. Lot Dimensions');
        row('Lot width (ft) - front face',  v(sd.lotWidth, 'ft'),              'Assessor record or GIS parcel data',                true);
        row('Lot depth (ft)',               v(sd.lotDepth, 'ft'),              'Assessor record or GIS parcel data',                false);
        row('Lot SF (assessor value)',       lotSF > 0 ? Math.round(lotSF).toLocaleString() + ' SF' : '--', 'Assessor record', true);
        row('Lot acres (lotSF / 43560)',     lotSF > 0 ? lotAC + ' AC' : '--', 'Calculated',                                       false);
        row('Irregular lot?',               hasPolygon ? 'Yes — polygon captured (' + sd.parcelPolygon.length + ' vertices)' : 'No (rectangular)', 'GIS parcel polygon', true);

        // C. Zoning Standards
        sec('C. Zoning Standards');
        row('Zone designation (exact code)', v(sd.zoning),                     'City zoning map / ZIMS zoning inquiry',             true);
        row('Base FAR',                      v(sd.baseFAR),                    'Municipal code — zoning district standards table',  false);
        row('Commercial FAR (mixed-use)',    v(sd.commFAR),                    'Municipal code — mixed-use or CCHS bonus table',    true);
        row('Max height base (ft)',          v(sd.baseHeightLimit || sd.maxHeight, 'ft'), 'Municipal code — height limits by zone', false);
        row('Max height with bonus (ft)',    v(sd.maxHeight, 'ft'),            'CCHS / density bonus provisions',                  true);
        row('CCHS max height cap (ft)',      v(sd.cchsMaxHeight, 'ft'),        'San Diego CCHS program — Tier 1/2/3 limits',       false);
        row('Front setback (ft)',            v(sd.frontSetback, 'ft'),         'Municipal code — setback standards for zone',       true);
        row('Rear setback (ft)',             v(sd.rearSetback, 'ft'),          'Municipal code — setback standards for zone',       false);
        row('Side setback (ft)',             v(sd.sideSetback, 'ft'),          'Municipal code — setback standards for zone',       true);
        row('Density: SF of lot per unit',   sd.densityPerSF > 0 ? '1 DU per ' + sd.densityPerSF + ' SF' : '--', 'Municipal code', false);
        row('Commercial frontage depth (ft)', v(sd.commercialDepth, 'ft'),    'CUPD/mixed-use code — min ground floor commercial depth', true);

        // D. Planning Overlays
        sec('D. Planning Overlays');
        var areas = sd.planningAreas || [];
        if (areas.length > 0) {
            areas.forEach(function(r, i) {
                row(r.name || ('Planning Area ' + (i+1)), r.val || '--', 'City General Plan / community plan document', i % 2 === 0);
            });
        } else {
            row('Planning areas', '--', 'City General Plan Land Use Map or zoning inquiry', true);
        }
        var overlays = sd.overlayZones || [];
        if (overlays.length > 0) {
            overlays.forEach(function(r, i) {
                row(r.name || ('Overlay Zone ' + (i+1)), r.val || '--', 'ZIMS zoning inquiry', i % 2 === 0);
            });
        } else {
            row('Overlay zones', '--', 'ZIMS zoning inquiry', false);
        }

        // E. Fees
        sec('E. Fees');
        row('NEF rate per SF',              v(sd.nefRatePerSF),               'City DSD Fee Schedule PDF — search NEF',            true);
        row('Affordability target %',        v(sd.affordabilityPct, '%'),      'State Gov Code 65915 — typically 10-24%',           false);
        row('DIF per unit',                  v(sd.difPerUnit),                 'City DSD DIF schedule — residential category',      true);
        row('DIF waiver SF threshold',       v(sd.difWaiverSF, 'SF'),         'City affordable housing DIF waiver policy',         false);

        // F. Project Info
        sec('F. Project Info');
        row('Project type',                  v(sd.projectType),                'e.g. 3-Story Townhome / Mixed-Use Residential',     true);
        row('Architect / firm name',         v(sd.architect),                  'Project team',                                      false);
        row('Scope of work',                 v(sd.scopeOfWork),                'What is demolished / built / program / units',      true);
        row('Notes',                         v(sd.notes),                      'Any unusual conditions: combined APNs, easements',  false);
        row('Occupancy group (proposed)',    v(sd.occupancyGroup),             'Based on project type: R-2, B, etc.',               true);
        row('Existing dwelling SF',          sd.existingDwellingSF > 0 ? sd.existingDwellingSF.toLocaleString() + ' SF' : '--', 'Assessor record', false);

        // G. Inspector Contacts
        sec('G. Inspector Contacts');
        var inspectors = sd.inspectors || [];
        if (inspectors.length > 0) {
            inspectors.forEach(function(ins, i) {
                row(ins.name || ('Inspector ' + (i+1)), ins.val || '--', 'City permit office / DSD staff directory', i % 2 === 0);
            });
        } else {
            row('Inspectors', '--', 'City permit office / DSD staff directory', true);
        }

        // H. Map Setup
        sec('H. Map Setup');
        row('Parcel centroid lat/lng',       (s.lat && s.lng) ? s.lat.toFixed(6) + ' / ' + s.lng.toFixed(6) : '--', 'Google Maps — right-click center — copy coordinates', true);
        row('Parcel polygon vertices',       hasPolygon ? sd.parcelPolygon.length + ' vertices captured' : 'Not set (rectangular lot assumed)', 'County GIS portal — parcel detail — export vertex lat/lng', false);
        row('Map rotation (degrees)',        s.rotation != null ? s.rotation.toFixed(1) + '°' : '--', 'Estimate from aerial: degrees lot north is off screen-north', true);
        row('Front bearing (degrees)',       s.frontBearing != null ? s.frontBearing.toFixed(2) + '°' : '--', 'Set Front Edge button in setback config', false);

        // ── Build HTML-as-XLS ────────────────────────────────────────────────────
        var C = {
            TITLE_BG:  '#64381F', TITLE_FG:  '#FFFFFF',
            HDR_BG:    '#64381F', HDR_FG:    '#FFFFFF',
            SEC_BG:    '#C47244', SEC_FG:    '#FFFFFF',
            ODD_A:     '#66D9FF', ODD_B:     '#F2F2F2',
            EVEN_A:    '#FFFFFF', EVEN_B:    '#FFFFFF',
            DONE_BG:   '#FFFFFF',
        };

        function esc(s) { return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }

        function tdStyle(bg, bold, size, wrap) {
            return 'background:' + bg + ';' +
                   (bold ? 'font-weight:bold;' : '') +
                   'font-size:' + (size || 10) + 'pt;' +
                   'color:' + (bg === C.TITLE_BG || bg === C.HDR_BG || bg === C.SEC_BG ? '#FFFFFF' : '#1a1a1a') + ';' +
                   'border:1px solid #999;padding:4px 6px;vertical-align:top;' +
                   (wrap ? 'white-space:normal;word-wrap:break-word;' : 'white-space:nowrap;');
        }

        var html = [
            '<html xmlns:o="urn:schemas-microsoft-com:office:office"',
            '      xmlns:x="urn:schemas-microsoft-com:office:excel">',
            '<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">',
            '<style>',
            '  body { font-family: Calibri, Arial, sans-serif; font-size: 10pt; }',
            '  table { border-collapse: collapse; width: 100%; }',
            '  td, th { border: 1px solid #999; padding: 4px 6px; vertical-align: top; font-size: 10pt; }',
            '</style></head><body>',
            '<table>',

            // Title
            '<tr>',
            '<td colspan="5" style="' + tdStyle(C.TITLE_BG, true, 13) + '">PROJECTBOOK-PLANNER — SITE DATA COLLECTION CHECKLIST &nbsp;&nbsp; ' + esc(sd.address || '') + '</td>',
            '</tr>',

            // Column headers
            '<tr>',
            '<th style="' + tdStyle(C.HDR_BG, true, 10) + ';width:140px">SECTION</th>',
            '<th style="' + tdStyle(C.HDR_BG, true, 10) + ';width:260px">FIELD / DATA POINT</th>',
            '<th style="' + tdStyle(C.HDR_BG, true, 10) + ';width:50px">DONE</th>',
            '<th style="' + tdStyle(C.HDR_BG, true, 10) + ';width:240px">VALUE COLLECTED</th>',
            '<th style="' + tdStyle(C.HDR_BG, true, 10) + ';width:240px">SOURCE / WHERE TO GET IT</th>',
            '</tr>',
        ];

        ROWS.forEach(function(r) {
            if (r.type === 'sec') {
                html.push(
                    '<tr>',
                    '<td colspan="5" style="' + tdStyle(C.SEC_BG, true, 10) + '">' + esc(r.label) + '</td>',
                    '</tr>'
                );
            } else {
                var abg = r.even ? C.EVEN_A : C.ODD_A;
                var bbg = r.even ? C.EVEN_B : C.ODD_B;
                var isDone = r.value && r.value !== '--';
                html.push(
                    '<tr>',
                    '<td style="' + tdStyle(abg, false, 10) + '"></td>',
                    '<td style="' + tdStyle(bbg, false, 10, true) + '">' + esc(r.field) + '</td>',
                    '<td style="background:#FFFFFF;border:1px solid #999;text-align:center;font-size:10pt;">' + (isDone ? '&#10003;' : '') + '</td>',
                    '<td style="' + tdStyle(abg, false, 10, true) + '">' + esc(r.value) + '</td>',
                    '<td style="' + tdStyle(bbg, false, 9, true) + '">' + esc(r.source) + '</td>',
                    '</tr>'
                );
            }
        });

        html.push('</table></body></html>');

        var blob = new Blob([html.join('\n')], { type: 'application/vnd.ms-excel;charset=utf-8' });
        var a = document.createElement('a');
        var _apn = (d.apn || 'Site').replace(/[^a-zA-Z0-9-]/g, '_');
        a.download = 'SiteDataChecklist_' + _apn + '.xls';
        a.href = URL.createObjectURL(blob);
        a.click();
        URL.revokeObjectURL(a.href);
    },

    generateInfoLISP: function() {
        const sd  = window.__SITE_DEFAULTS__ || {};
        const d   = ConfigEngine.data;
        const s   = ConfigEngine.state;

        const lotSF    = (d.lotSF && d.lotSF > 0) ? d.lotSF : (d.width * d.depth);
        const baseFAR  = sd.baseFAR  != null ? sd.baseFAR  : 2.0;
        const commFAR  = sd.commFAR  != null ? sd.commFAR  : 0;
        const maxHt    = sd.maxHeight != null ? sd.maxHeight : 50;
        const densPS   = sd.densityPerSF != null ? sd.densityPerSF : 600;
        const fSb      = sd.frontSetback != null ? sd.frontSetback : s.setbacks.front;
        const rSb      = sd.rearSetback  != null ? sd.rearSetback  : s.setbacks.rear;
        const sSb      = sd.sideSetback  != null ? sd.sideSetback  : s.setbacks.sideL;

        // Per-building variables
        var bldgLines = [];
        (s.buildings || []).forEach(function(b, i) {
            var n = i + 1;
            var sf = ((b.W || 0) * (b.D || 0) * (b.count || 1)).toFixed(0);
            bldgLines.push(
                '(setq SPI:Bldg' + n + 'W       ' + (b.W || 0).toFixed(1) + ')   ; ft',
                '(setq SPI:Bldg' + n + 'D       ' + (b.D || 0).toFixed(1) + ')   ; ft',
                '(setq SPI:Bldg' + n + 'Count   ' + (b.count || 1) + ')',
                '(setq SPI:Bldg' + n + 'Stories ' + (b.stories || 1) + ')',
                '(setq SPI:Bldg' + n + 'SF      ' + sf + ')   ; W x D x Count'
            );
        });

        // Planning areas as a nested list
        var planAreas = (sd.planningAreas || []).map(function(r) {
            return '  (list "' + (r.name || '').replace(/"/g, "'") + '" "' + (r.val || '').replace(/"/g, "'") + '")';
        });
        // Overlay zones as a nested list
        var overlays = (sd.overlayZones || []).map(function(r) {
            return '  (list "' + (r.name || '').replace(/"/g, "'") + '" "' + (r.val || '').replace(/"/g, "'") + '")';
        });

        var configSection = [
            ';; -- PROJECT IDENTITY --',
            '(setq SPI:Address     "' + (d.address || '').replace(/"/g, "'") + '")',
            '(setq SPI:APN         "' + (d.apn || '') + '")',
            '(setq SPI:Zone        "' + (d.zoning || '') + '")',
            '(setq SPI:LegalDesc   "' + (sd.legalDescription || '').replace(/"/g, "'") + '")',
            '(setq SPI:YearBuilt   "' + (sd.yearBuilt || '--') + '")',
            '(setq SPI:OccGroup    "' + (sd.occupancyGroup || '--') + '")',
            '(setq SPI:ProjType    "' + (sd.projectType || '--') + '")',
            '(setq SPI:Architect   "' + (sd.architect || '--') + '")',
            '',
            ';; -- LOT DIMENSIONS --',
            '(setq SPI:LotWidth    ' + (d.width  || 0).toFixed(1) + ')   ; ft',
            '(setq SPI:LotDepth    ' + (d.depth  || 0).toFixed(1) + ')   ; ft',
            '(setq SPI:LotSF       ' + Math.round(lotSF) + ')   ; sq ft',
            '',
            ';; -- SETBACKS --',
            '(setq SPI:FrontSb     ' + Number(fSb).toFixed(1) + ')   ; ft',
            '(setq SPI:RearSb      ' + Number(rSb).toFixed(1) + ')   ; ft',
            '(setq SPI:SideSb      ' + Number(sSb).toFixed(1) + ')   ; ft',
            '',
            ';; -- ZONING PARAMETERS --',
            '(setq SPI:BaseFAR     ' + Number(baseFAR).toFixed(2) + ')',
            '(setq SPI:CommFAR     ' + Number(commFAR).toFixed(2) + ')',
            '(setq SPI:MaxHeight   ' + Number(maxHt).toFixed(1) + ')   ; ft',
            '(setq SPI:DensityPerSF ' + Number(densPS).toFixed(0) + ')',
            '(setq SPI:BuildableSF (fix (* SPI:LotSF SPI:BaseFAR)))',
            '',
            ';; -- PLANNING & OVERLAY --',
            '(setq SPI:PlanningAreas (list',
            (planAreas.length ? planAreas.join('\n') : '  nil'),
            '))',
            '(setq SPI:OverlayZones (list',
            (overlays.length ? overlays.join('\n') : '  nil'),
            '))',
            '',
            ';; -- PROPOSED BUILDINGS (' + (s.buildings || []).length + ') --',
            '(setq SPI:BldgCount ' + (s.buildings || []).length + ')',
        ].concat(bldgLines).join('\n');

        var today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' });

        var skeleton = [
            ';;; ====================================================================',
            ';;; SiteProjectInfo.lsp',
            ';;; ====================================================================',
            ';;; PURPOSE: Load site project data variables into AutoCAD session.',
            ';;;   Variables use the SPI: namespace and remain in-session.',
            ';;; COMMAND: SPI -> prints all site info to text screen',
            ';;; GENERATED: ' + today + ' by ProjectBook-Planner',
            ';;; ====================================================================',
            '',
            ';;; ==========================================================================',
            ';;; CONFIG',
            ';;; APN:     ' + (d.apn || ''),
            ';;; Address: ' + (d.address || ''),
            ';;; ==========================================================================',
            '',
            configSection,
            '',
            ';;; ==========================================================================',
            ';;; COMMAND: SPI -- Print site info',
            ';;; ==========================================================================',
            '',
            '(defun c:SPI ()',
            '  (textscr)',
            '  (princ "\\n=======================================================")',
            '  (princ "\\n  SITE PROJECT INFO")',
            '  (princ "\\n=======================================================")',
            '  (princ (strcat "\\n  Address:      " SPI:Address))',
            '  (princ (strcat "\\n  APN:          " SPI:APN))',
            '  (princ (strcat "\\n  Zone:         " SPI:Zone))',
            '  (princ (strcat "\\n  Legal:        " SPI:LegalDesc))',
            '  (princ (strcat "\\n  Year Built:   " SPI:YearBuilt))',
            '  (princ (strcat "\\n  Occupancy:    " SPI:OccGroup))',
            '  (princ (strcat "\\n  Project Type: " SPI:ProjType))',
            '  (princ (strcat "\\n  Architect:    " SPI:Architect))',
            '  (princ "\\n-------------------------------------------------------")',
            '  (princ (strcat "\\n  Lot Width:    " (rtos SPI:LotWidth  2 1) " ft"))',
            '  (princ (strcat "\\n  Lot Depth:    " (rtos SPI:LotDepth  2 1) " ft"))',
            '  (princ (strcat "\\n  Lot SF:       " (itoa SPI:LotSF) " sq.ft."))',
            '  (princ "\\n-------------------------------------------------------")',
            '  (princ (strcat "\\n  Front Setback:" (rtos SPI:FrontSb 2 1) " ft"))',
            '  (princ (strcat "\\n  Rear Setback: " (rtos SPI:RearSb  2 1) " ft"))',
            '  (princ (strcat "\\n  Side Setback: " (rtos SPI:SideSb  2 1) " ft"))',
            '  (princ "\\n-------------------------------------------------------")',
            '  (princ (strcat "\\n  Base FAR:     " (rtos SPI:BaseFAR   2 2)))',
            '  (princ (strcat "\\n  Comm FAR:     " (rtos SPI:CommFAR   2 2)))',
            '  (princ (strcat "\\n  Max Height:   " (rtos SPI:MaxHeight 2 1) " ft"))',
            '  (princ (strcat "\\n  Buildable SF: " (itoa SPI:BuildableSF) " sq.ft."))',
            '  (princ "\\n-------------------------------------------------------")',
            '  (princ (strcat "\\n  Buildings:    " (itoa SPI:BldgCount)))',
            '  (princ "\\n=======================================================")',
            '  (princ)',
            ')',
            '',
            '(defun c:SiteProjectInfo () (c:SPI))',
            '',
            ';;; ==========================================================================',
            ';;; LOAD MESSAGE',
            ';;; ==========================================================================',
            '',
            '(princ "\\n=======================================================")',
            '(princ "\\n :: SiteProjectInfo.lsp [SPI] Loaded")',
            '(princ (strcat "\\n :: APN:  " SPI:APN))',
            '(princ "\\n :: Command: SPI")',
            '(princ "\\n=======================================================")',
            '(princ)'
        ].join('\n');

        const blob = new Blob([skeleton], { type: 'text/plain' });
        const link = document.createElement('a');
        var _apn = (d.apn || 'Site').replace(/[^a-zA-Z0-9-]/g, '_');
        link.download = 'SiteProjectInfo_' + _apn + '.lsp';
        link.href = URL.createObjectURL(blob);
        link.click();
        URL.revokeObjectURL(link.href);
    },

    exportImage: function() {
        html2canvas(document.getElementById('map'), { useCORS: true, allowTaint: false, backgroundColor: null })
            .then(canvas => {
                const link = document.createElement('a');
                link.download = `Vicinity_Map_${ConfigEngine.data.apn}.png`;
                link.href = canvas.toDataURL("image/png");
                link.click();
            })
            .catch(() => {
                alert("Image export blocked by tile server security. Use the Fullscreen button and take a screenshot instead.");
            });
    },

    // ══════════════════════════════════════════════════════════════════
    //  SINGLE SAVE — every button in the app calls this ONE function.
    //  1. Syncs all UI inputs -> ConfigEngine.state
    //  2. Writes _payload() to ONE localStorage key
    //  3. Pushes to dev server (no-op outside localhost)
    //  4. Shows flash badge
    // ══════════════════════════════════════════════════════════════════
    save: function() {
        const s = ConfigEngine.state;

        // ── Sync setback inputs ──
        const sbF = document.getElementById('sb-front');
        if (sbF) {
            s.setbacks = {
                front: parseFloat(sbF.value) || 0,
                rear:  parseFloat(document.getElementById('sb-rear').value) || 0,
                sideL: parseFloat(document.getElementById('sb-side-l').value) || 0,
                sideR: parseFloat(document.getElementById('sb-side-r').value) || 0
            };
        }

        // ── Sync active building inputs ──
        const bldg = s.buildings[s.activeBuilding];
        if (bldg) {
            const el = function(id) { return document.getElementById(id); };
            if (el('bldgOrientInput'))  bldg.orientation  = parseFloat(el('bldgOrientInput').value) || 0;
            if (el('bldgW'))            bldg.W            = parseFloat(el('bldgW').value) || 30;
            if (el('bldgD'))            bldg.D            = parseFloat(el('bldgD').value) || 60;
            if (el('bldgOffsetX'))      bldg.offsetX      = parseFloat(el('bldgOffsetX').value) || 0;
            if (el('bldgOffsetY'))      bldg.offsetY      = parseFloat(el('bldgOffsetY').value) || 0;
            if (el('bldgCount'))        bldg.count        = parseInt(el('bldgCount').value) || 1;
            if (el('bldgStackSpacing')) bldg.stackSpacing  = parseFloat(el('bldgStackSpacing').value) || 0;
            if (el('bldgStackAngle'))   bldg.stackAngle    = parseFloat(el('bldgStackAngle').value)   || 0;
            if (el('bldgStories'))      bldg.stories      = parseInt(el('bldgStories').value) || 1;
            if (el('bldgFloorHeight'))  bldg.floorHeight  = parseFloat(el('bldgFloorHeight').value) || 9;
            var anchors = {anchorFront:'front', anchorCenter:'center', anchorRear:'rear'};
            Object.keys(anchors).forEach(function(id) {
                var btn = document.getElementById(id);
                if (btn && btn.classList.contains('active')) bldg.anchor = anchors[id];
            });
        }

        // ── Sync toggles ──
        var cf = document.getElementById('commFrontCheck');
        if (cf) s.commFront = cf.checked;
        // Sync MapEngine UI state -> ConfigEngine.state (single source of truth)
        if (typeof MapEngine !== 'undefined') {
            if (MapEngine.showBldgDims != null)  s.showBldgDims  = MapEngine.showBldgDims;
            if (MapEngine.hiddenDimKeys)         s.hiddenDimKeys  = [...MapEngine.hiddenDimKeys];
            if (MapEngine.mergedDimKeys)         s.mergedDimKeys  = [...MapEngine.mergedDimKeys];
            if (MapEngine.chainWOffset != null)  s.chainWOffset  = MapEngine.chainWOffset;
            if (MapEngine.chainDOffset != null)  s.chainDOffset  = MapEngine.chainDOffset;
            if (MapEngine._propDimOffsets)        s.propDimOffsets = MapEngine._propDimOffsets;
        }

        // ── Persist: ONE key ──
        try { localStorage.setItem('site_state', JSON.stringify(this._payload())); }
        catch(e) { console.warn('Save to localStorage failed:', e.message); }

        // ── Push to dev server (no-op outside localhost) ──
        this._pushToServer();

        // ── Flash badge ──
        this._showFlash();
    },

    // Shared payload builder -- single source of truth for all persisted state.
    _payload: function() {
        var s = ConfigEngine.state;
        var payload = {
            project: 'ProjectBook-Planner',
            siteId: ConfigEngine.data.siteId || null,
            saved: {
                lat:            s.lat,
                lng:            s.lng,
                rotation:       s.rotation,
                locked:         s.locked,
                setbacks:       s.setbacks,
                buildings:      s.buildings,
                activeBuilding: s.activeBuilding,
                commFront:      s.commFront,
                showBldgDims:   s.showBldgDims  ?? false,
                hiddenDimKeys:  s.hiddenDimKeys  ? [...s.hiddenDimKeys] : [],
                mergedDimKeys:  s.mergedDimKeys  ? [...s.mergedDimKeys] : [],
                chainWOffset:   s.chainWOffset  ?? 0,
                chainDOffset:   s.chainDOffset  ?? 0,
                propDimOffsets:  s.propDimOffsets || {},
                parcelPolygon:  ConfigEngine.data.parcelPolygon || null,
                mapOpacity:     s.mapOpacity,
                setbacksApplied: s.setbacksApplied,
                freeDrag:       s.freeDrag ?? true,
                snapEdge:       s.snapEdge ?? true,
                siteNorthDeg:   s.siteNorthDeg ?? 0,
                frontBearing:   s.frontBearing ?? 270,
                vehicles:       s.vehicles || [],
                activeVehicle:  s.activeVehicle ?? -1,
                existingBuildings: s.existingBuildings || [],
                activeExBuilding:  s.activeExBuilding  ?? -1,
                _geoOffsets: true
            }
        };
        // Include checklist state if available (shared localStorage on same origin)
        try {
            var ckRaw = null;
            for (var i = 0; i < localStorage.length; i++) {
                var k = localStorage.key(i);
                if (k && k.indexOf('preapp_') === 0) { ckRaw = localStorage.getItem(k); break; }
            }
            if (ckRaw) payload.checklist = JSON.parse(ckRaw);
        } catch(e) { console.warn('[EXPORT] Checklist parse failed — checklist will not be included in save:', e.message); }
        return payload;
    },

    // Show the fixed save flash badge for 2 seconds
    _showFlash: function() {
        var el = document.getElementById('map-save-flash');
        if (!el) return;
        if (this._flashTimer) clearTimeout(this._flashTimer);
        el.style.display = 'block';
        el.style.animation = 'none';
        void el.offsetWidth;
        el.style.animation = '';
        this._flashTimer = setTimeout(function() { el.style.display = 'none'; }, 2000);
    },

    // Background push to local dev server
    _pushToServer: function() {
        if (window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') return;
        var self = this;
        fetch('/save', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(this._payload(), null, 2)
        }).then(function(r) {
            if (!r.ok) self._showSaveError('Server returned ' + r.status);
        }).catch(function(err) {
            self._showSaveError('Server unreachable');
        });
    },

    _showSaveError: function(msg) {
        var el = document.getElementById('map-save-flash');
        if (!el) { console.warn('Save failed:', msg); return; }
        if (this._flashTimer) clearTimeout(this._flashTimer);
        el.textContent = 'Save failed: ' + msg;
        el.style.display = 'block';
        el.style.background = '#c53030';
        el.style.animation = 'none';
        var self = this;
        this._flashTimer = setTimeout(function() {
            el.style.display = 'none';
            el.textContent = 'Saved';
            el.style.background = '';
        }, 4000);
    },

    // Save to File button — save() + download on file://
    saveToFile: function() {
        this.save();
        var btn = document.getElementById('saveSettingsBtn');
        if (btn) { btn.textContent = 'Saved!'; btn.style.background = '#2f855a'; setTimeout(function() { btn.textContent = 'Save to File'; btn.style.background = ''; }, 1800); }
        // file:// fallback: also download
        if (window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
            var blob = new Blob([JSON.stringify(this._payload(), null, 2)], { type: 'application/json' });
            var a = document.createElement('a');
            a.href = URL.createObjectURL(blob); a.download = 'site-data.json'; a.click();
            URL.revokeObjectURL(a.href);
        }
    },

    // FAB download — save() + always download JSON
    downloadConfig: function() {
        this.save();
        var blob = new Blob([JSON.stringify(this._payload(), null, 2)], { type: 'application/json' });
        var a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'site-data.json';
        a.click();
        URL.revokeObjectURL(a.href);
    }
};
