"""completion_gate.py — Hard gate before declaring any task done.

Enforces the Completion Protocol (GLOBAL-006 Part A). Must pass before any
agent declares a task complete. Exit 1 = BLOCKED.

Checks:
    1. No stale artifacts in active paths (__pycache__, *.bak, *.tmp, etc.)
    2. All tests pass (pytest tests/)
    3. WMF agent dry-run succeeds (wmf_agent.py)
    4. No unread pings in controller-note/

Usage:
    py tools/completion_gate.py              # strict mode
    py tools/completion_gate.py --allow-dirty  # skip uncommitted-work check

Uses content-based ISO timestamp comparison (not mtime) for ping checks.
Derives all paths from cwd — no hardcoded paths (GLOBAL-004).
"""
from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_ISO_RE = re.compile(
    r"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"
    r"(?:\.\d+)?(?:[+-]\d{2}:\d{2}|Z)?)"
)


def _parse_ts(path: Path) -> datetime | None:
    """Parse ISO timestamp from .ping or .last-read file content."""
    if not path.exists():
        return None
    try:
        text = path.read_text(encoding="utf-8").strip()
    except OSError:
        try:
            return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        except OSError:
            return None
    if not text:
        return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    m = _ISO_RE.search(text)
    if m:
        raw = m.group(1)
        if raw.endswith("Z"):
            raw = raw[:-1] + "+00:00"
        try:
            dt = datetime.fromisoformat(raw)
            return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
        except ValueError:
            pass
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)


def _run(cmd: list[str], cwd: Path | None = None,
         timeout: int = 120) -> tuple[int, str]:
    """Run command, return (returncode, combined stdout+stderr)."""
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=cwd, timeout=timeout,
        )
        return result.returncode, result.stdout + result.stderr
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        return 1, str(exc)


def _clean_runtime_artifacts(repo_root: Path) -> None:
    """Remove __pycache__ and .pytest_cache generated by gate checks."""
    import shutil

    skip = {".venv", ".git", "node_modules"}
    for dirname in ("__pycache__", ".pytest_cache"):
        for hit in repo_root.rglob(dirname):
            if any(part in hit.parts for part in skip):
                continue
            if hit.is_dir():
                shutil.rmtree(hit, ignore_errors=True)


def check_stale(repo_root: Path) -> list[str]:
    """Return list of stale artifact paths found in the repo."""
    stale_patterns = ("*.bak", "*.old", "*.orig", "*.tmp", "*~", "*.copy", "*.rej", "*.pyc")
    stale_dirs = ("__pycache__", ".pytest_cache")
    skip_dirs = {".venv", ".git", "node_modules", "report/archive"}
    found: list[str] = []

    for pattern in stale_patterns:
        for hit in repo_root.rglob(pattern):
            if any(part in hit.parts for part in skip_dirs):
                continue
            found.append(str(hit.relative_to(repo_root)))

    for dirname in stale_dirs:
        for hit in repo_root.rglob(dirname):
            if any(part in hit.parts for part in skip_dirs):
                continue
            if not hit.is_dir():
                continue
            try:
                has_contents = any(hit.iterdir())
            except (PermissionError, OSError):
                continue
            if has_contents:
                found.append(str(hit.relative_to(repo_root)) + "/")

    return found


def main() -> int:
    allow_dirty = "--allow-dirty" in sys.argv
    repo_root = Path.cwd().resolve()
    rc, out = _run(["git", "rev-parse", "--show-toplevel"], cwd=repo_root)
    if rc == 0 and out.strip():
        repo_root = Path(out.strip())

    print(f"completion_gate: {repo_root.name}")
    print("=" * 50)
    failures: list[str] = []

    _clean_runtime_artifacts(repo_root)

    # 1. Unread pings
    ping = repo_root / "controller-note" / ".ping"
    last_read = repo_root / "controller-note" / ".last-read"
    ping_ts = _parse_ts(ping)
    if ping_ts is not None:
        read_ts = _parse_ts(last_read)
        if read_ts is None or ping_ts > read_ts:
            failures.append("PING: unread ping in controller-note/")
        else:
            print("[PASS] No unread pings")
    else:
        print("[PASS] No unread pings")

    # 2. Tests
    tests_dir = repo_root / "tests"
    if tests_dir.exists() and any(tests_dir.glob("test_*.py")):
        print("[....] Running pytest...")
        rc, out = _run(
            [sys.executable, "-m", "pytest", "tests/", "-q", "--tb=short"],
            cwd=repo_root,
        )
        if rc != 0:
            for line in out.splitlines():
                if "failed" in line or "error" in line.lower():
                    failures.append(f"TESTS: {line.strip()}")
                    break
            else:
                failures.append("TESTS: pytest exited non-zero")
        else:
            lines = [ln for ln in out.splitlines() if ln.strip()]
            print(f"[PASS] {lines[-1] if lines else 'all passed'}")
    else:
        print("[SKIP] No tests found in tests/ — skipping pytest")

    # 3. WMF agent dry-run
    wmf = repo_root / "src" / "agents" / "wmf_agent.py"
    if wmf.exists():
        print("[....] Running wmf_agent dry-run...")
        rc, out = _run(
            [sys.executable, str(wmf), "--dry-run"],
            cwd=repo_root,
            timeout=60,
        )
        if rc != 0:
            # wmf_agent may not support --dry-run yet; warn but don't block
            print(f"[WARN] wmf_agent --dry-run returned {rc} (may not support flag)")
        else:
            print("[PASS] wmf_agent dry-run OK")
    else:
        print("[SKIP] wmf_agent.py not found — skipping")

    # 4. Stale artifacts post-clean check
    _clean_runtime_artifacts(repo_root)
    post_stale = check_stale(repo_root)
    if post_stale:
        failures.append(f"STALE: {len(post_stale)} artifact(s) remain after cleanup")
        for s in post_stale[:5]:
            print(f"  stale: {s}")

    print("=" * 50)
    if failures:
        print(f"BLOCKED: {len(failures)} gate(s) failed:")
        for f in failures:
            print(f"  - {f}")
        print("\nFix all failures before declaring done.")
        return 1

    print("COMPLETION GATE PASSED — task may be declared done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
